//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_SUPPLIERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_SUPPLIERS()
        {
            this.MAS_SUPPLIER_CONTACTS = new HashSet<MAS_SUPPLIER_CONTACTS>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string TaxID { get; set; }
        public string ReferCode { get; set; }
        public byte TypeID { get; set; }
        public byte GroupID { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public int DistrictID { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Remark { get; set; }
        public byte Status { get; set; }
        public string ReferCode01 { get; set; }
        public string ReferCode02 { get; set; }
        public string ReferCode03 { get; set; }
        public string ReferCode04 { get; set; }
        public string ReferCode05 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_SUPPLIER_CONTACTS> MAS_SUPPLIER_CONTACTS { get; set; }
        public virtual SYS_DISTRICTS SYS_DISTRICTS { get; set; }
    }
}
