//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CORE_BUSINESS_COMPANY
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string Name { get; set; }
        public string NameTHLong { get; set; }
        public string NameENLong { get; set; }
        public string JobCodeFormat { get; set; }
        public string TaxID { get; set; }
        public string BussinessAddressOne { get; set; }
        public string BussinessAddressTwo { get; set; }
        public string BussinessAddressThree { get; set; }
        public string Description { get; set; }
        public bool SystemDefault { get; set; }
        public byte Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
