//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CUSTOMER_LOCATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_CUSTOMER_LOCATIONS()
        {
            this.TRN_JOBS = new HashSet<TRN_JOBS>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Name { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public int DistrictID { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string GpsLocation { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> ServiceSupportID { get; set; }
        public Nullable<System.TimeSpan> WeekOfficeHourStart { get; set; }
        public Nullable<System.TimeSpan> WeekOfficeHourEnd { get; set; }
        public Nullable<System.TimeSpan> WeekendOfficeHourStart { get; set; }
        public Nullable<System.TimeSpan> WeekendOfficeHourEnd { get; set; }
        public bool DefalutLocation { get; set; }
        public bool BillingLocation { get; set; }
        public bool ProjectSite { get; set; }
        public bool AssetLocation { get; set; }
        public bool OtherLocation { get; set; }
        public string Remark { get; set; }
        public byte System_Flag { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MAS_CUSTOMER_CONTACTS MAS_CUSTOMER_CONTACTS { get; set; }
        public virtual MAS_CUSTOMERS MAS_CUSTOMERS { get; set; }
        public virtual SYS_DISTRICTS SYS_DISTRICTS { get; set; }
        public virtual MAS_ZONE MAS_ZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_JOBS> TRN_JOBS { get; set; }
    }
}
