//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_EMAIL_TEMPLATE
    {
        public decimal email_id { get; set; }
        public string email_name { get; set; }
        public string email_type { get; set; }
        public bool email_flag { get; set; }
        public string email_data { get; set; }
        public Nullable<System.DateTime> email_create_date { get; set; }
        public Nullable<System.DateTime> email_update_date { get; set; }
    }
}
