//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_ZONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_ZONE()
        {
            this.MAS_CUSTOMER_LOCATIONS = new HashSet<MAS_CUSTOMER_LOCATIONS>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Distance { get; set; }
        public decimal TranspotFee { get; set; }
        public string Description { get; set; }
        public Nullable<byte> System_Flag { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_CUSTOMER_LOCATIONS> MAS_CUSTOMER_LOCATIONS { get; set; }
    }
}
