//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_COMPONENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_COMPONENTS()
        {
            this.SYS_COMPONENTS1 = new HashSet<SYS_COMPONENTS>();
            this.SYS_ROLES_PERMISSIONS = new HashSet<SYS_ROLES_PERMISSIONS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public byte Types { get; set; }
        public byte Levels { get; set; }
        public string Caption { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionCaption { get; set; }
        public Nullable<short> ScreenSequence { get; set; }
        public string URL { get; set; }
        public string API { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<byte> SystemComponent { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string IconName { get; set; }
        public byte System_Flag { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_COMPONENTS> SYS_COMPONENTS1 { get; set; }
        public virtual SYS_COMPONENTS SYS_COMPONENTS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_ROLES_PERMISSIONS> SYS_ROLES_PERMISSIONS { get; set; }
    }
}
