//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIGS
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string StringValue { get; set; }
        public string DisplayOption { get; set; }
        public string Description { get; set; }
    }
}
