//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SYSTEM_LOGS
    {
        public long ID { get; set; }
        public string ActionLog { get; set; }
        public string TableName { get; set; }
        public string ObjectName { get; set; }
        public string ReferenceKeyID { get; set; }
        public string SystemInformation { get; set; }
        public string UserName { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string ReferenceNumber01 { get; set; }
        public string ReferenceNumber02 { get; set; }
        public string ReferenceNumber03 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remark { get; set; }
    }
}
