//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DOCUMENT_PATTERNS
    {
        public byte id { get; set; }
        public string Code { get; set; }
        public string Pattern { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string LatestNumber { get; set; }
        public string Remark { get; set; }
    }
}
