//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PROVINCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_PROVINCES()
        {
            this.SYS_DISTRICTS = new HashSet<SYS_DISTRICTS>();
            this.TRN_JOBS = new HashSet<TRN_JOBS>();
        }
    
        public short ID { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string NameOther { get; set; }
        public string PostCode { get; set; }
        public Nullable<byte> RegionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_DISTRICTS> SYS_DISTRICTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_JOBS> TRN_JOBS { get; set; }
    }
}
