//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_AUTHORIZED_APPLICATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_AUTHORIZED_APPLICATIONS()
        {
            this.SYS_AUTHORIZATION_LOGS = new HashSet<SYS_AUTHORIZATION_LOGS>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ApplicationKey { get; set; }
        public Nullable<byte> CookieExpireDays { get; set; }
        public Nullable<byte> TokenExpireDays { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_AUTHORIZATION_LOGS> SYS_AUTHORIZATION_LOGS { get; set; }
    }
}
