//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_EMAIL_CONFIGS
    {
        public int ID { get; set; }
        public string TemplateKey { get; set; }
        public string SenderName { get; set; }
        public string EmailSender { get; set; }
        public string EmailTo { get; set; }
        public string EmailAutoCC { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBodyContent { get; set; }
        public Nullable<short> MailDelay { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpServerPort { get; set; }
        public string SmtpAuthorizeAccount { get; set; }
        public string SmtpAutohorizeSecret { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
