//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ROLES_PERMISSIONS
    {
        public int ID { get; set; }
        public int ComponentID { get; set; }
        public int PermissionID { get; set; }
        public int RoleID { get; set; }
        public bool Allow { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SYS_COMPONENTS SYS_COMPONENTS { get; set; }
        public virtual SYS_PERMISSIONS SYS_PERMISSIONS { get; set; }
        public virtual SYS_ROLES SYS_ROLES { get; set; }
    }
}
