//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSoft.Claim.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_JOBS
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string ReferenceCode { get; set; }
        public int ServicesOrderTypeID { get; set; }
        public int ServicesTypeID { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<byte> Difficulty { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> PmPlanID { get; set; }
        public Nullable<bool> Rework { get; set; }
        public Nullable<byte> ReworkNumber { get; set; }
        public Nullable<bool> Refix { get; set; }
        public Nullable<byte> RefixNumber { get; set; }
        public byte TransferType { get; set; }
        public Nullable<int> TransferFromBuID { get; set; }
        public Nullable<byte> TransferCauseID { get; set; }
        public Nullable<byte> ProblemType { get; set; }
        public string ProblemDetail { get; set; }
        public string Remark { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> IndirectCustomerID { get; set; }
        public string CustomerReferNumber { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<short> ProvinceID { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string GpsLocation { get; set; }
        public string CheckInLocation { get; set; }
        public string CheckOutLocation { get; set; }
        public Nullable<int> OpenJobBuID { get; set; }
        public int BuID { get; set; }
        public Nullable<byte> OnsiteBD { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SdmID { get; set; }
        public Nullable<int> OpenerID { get; set; }
        public Nullable<int> TerminatorID { get; set; }
        public Nullable<int> EngineerID01 { get; set; }
        public Nullable<int> EngineerID02 { get; set; }
        public Nullable<int> EngineerID03 { get; set; }
        public Nullable<int> EngineerID04 { get; set; }
        public Nullable<int> EngineerID05 { get; set; }
        public Nullable<int> EngineerAcceptedJobID { get; set; }
        public Nullable<int> EngineerFinalJobID { get; set; }
        public Nullable<int> SopSupplierID { get; set; }
        public Nullable<int> SopEngineerID { get; set; }
        public string InformeBy { get; set; }
        public Nullable<int> InformeTypeID { get; set; }
        public Nullable<System.DateTime> InformedDate { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> ExpectedResponseDate { get; set; }
        public Nullable<System.DateTime> ExpectedFixedDate { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> NextAppointmentDate { get; set; }
        public Nullable<System.DateTime> TravelStartDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<System.DateTime> FixStartDate { get; set; }
        public Nullable<System.DateTime> FixEndDate { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> ExternalFixingTypeID { get; set; }
        public Nullable<int> ExternalSupplierID { get; set; }
        public Nullable<System.DateTime> ExternalSentDate { get; set; }
        public Nullable<System.DateTime> ExternalReturnDate { get; set; }
        public Nullable<decimal> ExternalFixingCost { get; set; }
        public string ExternalRemark { get; set; }
        public Nullable<int> OverSlaID { get; set; }
        public string OverSlaRemark { get; set; }
        public Nullable<short> OverSlaDays { get; set; }
        public Nullable<short> OverSlaHours { get; set; }
        public Nullable<short> OverSlaMinutes { get; set; }
        public Nullable<short> WorkingDays { get; set; }
        public Nullable<short> WorkingHours { get; set; }
        public Nullable<short> WorkingMinutes { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<decimal> AmountSpareParts { get; set; }
        public Nullable<decimal> AmountServices { get; set; }
        public Nullable<decimal> AmountTransport { get; set; }
        public Nullable<decimal> AmountOther { get; set; }
        public Nullable<decimal> AmountNoDiscount { get; set; }
        public Nullable<decimal> AmountDiscount { get; set; }
        public Nullable<decimal> AmountWithDiscount { get; set; }
        public Nullable<decimal> AdditionalDiscount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> VATRate { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> EstimatedAmountSpareParts { get; set; }
        public Nullable<decimal> EstimatedAmountServices { get; set; }
        public Nullable<decimal> EstimatedAmountTransport { get; set; }
        public Nullable<decimal> EstimatedAmountOther { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public string CreditRemark { get; set; }
        public string ReferNumber01 { get; set; }
        public string ReferNumber02 { get; set; }
        public string ReferNumber03 { get; set; }
        public string ReferNumber04 { get; set; }
        public string ReferNumber05 { get; set; }
        public Nullable<int> LastestActionID { get; set; }
        public Nullable<int> LastestLogID { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> EditSlaDate01 { get; set; }
        public Nullable<System.DateTime> EditSlaDate02 { get; set; }
        public Nullable<System.DateTime> EditSlaDate03 { get; set; }
        public Nullable<System.DateTime> EditSlaDate04 { get; set; }
        public Nullable<System.DateTime> EditSlaDate05 { get; set; }
        public Nullable<System.DateTime> EditSlaDate06 { get; set; }
        public Nullable<System.DateTime> EditSlaDate07 { get; set; }
        public Nullable<System.DateTime> EditSlaDate08 { get; set; }
        public Nullable<System.DateTime> EditSlaDate09 { get; set; }
        public Nullable<System.DateTime> EditSlaDate10 { get; set; }
        public Nullable<int> EditOverSlaID { get; set; }
        public string EditOverSlaRemark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string NewModelName { get; set; }
        public string SenderName { get; set; }
        public Nullable<decimal> ExternalFixingMaterialCost { get; set; }
        public string TravelStartLocation { get; set; }
        public Nullable<decimal> TotalTravelDistance { get; set; }
        public Nullable<System.DateTime> PartyArrivalDate { get; set; }
        public Nullable<System.DateTime> CustomerArrivalDate { get; set; }
        public Nullable<System.DateTime> CustomerApproveDate { get; set; }
        public Nullable<int> JobRunNo { get; set; }
        public string InsuranceClaimNo { get; set; }
        public string RefPickup { get; set; }
        public string SupplierCliamNumber { get; set; }
        public Nullable<int> RefJobID { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string NoteToEngineer { get; set; }
        public Nullable<bool> IsOnsiteMachineArrived { get; set; }
        public Nullable<System.DateTime> DepartDate { get; set; }
        public string DepartBy { get; set; }
        public Nullable<System.DateTime> AllowanceStartDate { get; set; }
        public Nullable<System.DateTime> AllowanceEndDate { get; set; }
        public string LicensePlate { get; set; }
        public string TravelDistance { get; set; }
        public Nullable<int> TrxProductBufferID { get; set; }
        public Nullable<byte> EquipmentType { get; set; }
    
        public virtual MAS_CUSTOMER_CONTACTS MAS_CUSTOMER_CONTACTS { get; set; }
        public virtual MAS_CUSTOMER_LOCATIONS MAS_CUSTOMER_LOCATIONS { get; set; }
        public virtual MAS_CUSTOMERS MAS_CUSTOMERS { get; set; }
        public virtual MAS_CUSTOMERS MAS_CUSTOMERS1 { get; set; }
        public virtual SYS_DISTRICTS SYS_DISTRICTS { get; set; }
        public virtual SYS_PROVINCES SYS_PROVINCES { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
